vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            uri_prefix: '%app.path.product_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.product_images%'
            delete_on_remove: true
            delete_on_update: true

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
